image: docker:stable

services:
  - docker:dind

stages:
  - build
  - deploy

build-frontend-dev:
  stage: build
  before_script:
    - docker --version
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - apk update && apk add -U git tzdata
    - BACKEND_SERVER_URL=https://dev.marco79423.net
    - SITE_VERSION=`git describe --tags`
    - SITE_UPDATED_TIME=`TZ=Asia/Taipei date -Iseconds`
  script:
    - docker build
      --file frontend/Dockerfile
      --build-arg BACKEND_SERVER_URL=$BACKEND_SERVER_URL
      --build-arg SITE_VERSION=$SITE_VERSION
      --build-arg SITE_UPDATED_TIME=$SITE_UPDATED_TIME
      --tag marco79423/mysite-frontend:latest
      .
    - docker push marco79423/mysite-frontend:latest
    - docker tag marco79423/mysite-frontend:latest marco79423/mysite-frontend:$CI_COMMIT_REF_NAME
    - docker push marco79423/mysite-frontend:$CI_COMMIT_REF_NAME

build-backend-dev:
  stage: build
  before_script:
    - docker --version
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
    - apk update && apk add -U git tzdata
    - BACKEND_SERVER_URL=https://dev.marco79423.net
    - SITE_VERSION=`git describe --tags`
  script:
    - docker build
      --file backend/Dockerfile
      --build-arg BACKEND_SERVER_URL=$BACKEND_SERVER_URL
      --build-arg BACKEND_SECRET_KEY=$BACKEND_SECRET_KEY
      --build-arg SITE_VERSION=$SITE_VERSION
      --tag marco79423/mysite-backend:latest
      .
    - docker push marco79423/mysite-backend:latest
    - docker tag marco79423/mysite-backend:latest marco79423/mysite-backend:$CI_COMMIT_REF_NAME
    - docker push marco79423/mysite-backend:$CI_COMMIT_REF_NAME

.deploy-template: &deploy-template
  image: python:3
  stage: deploy
  before_script:
    - pip install -r requirements-deploy.txt
    - echo "$PROJECT_CONFIG" > project_config.json
    - echo "$SSH_PRIVATE_KEY" > my_aws.pem
  when: on_success

deploy-dev:
  <<: *deploy-template
  except:
    - tags
  script:
    - python contl.py deploy
  environment:
    name: development
    url: https://dev.marco79423.net

deploy-prod:
  <<: *deploy-template
  only:
    - tags
  script:
    - python contl.py deploy --prod
  environment:
    name: production
    url: https://marco79423.net
