matrix:
  include:
    - language: node_js
      node_js: "6"
      before_install:
        - cd frontend
      install:
        - yarn
      script:
        - yarn test
      cache:
        directories:
          - "frontend/node_modules"
    - language: python
      python: "3.5"
      before_install:
        - cd backend
      install:
        - pip install -r requirements.txt
      before_script:
        - cd src
      script:
        - python manage.py test

