matrix:
  include:
    - sudo: required
      language: node_js
      before_script:
        - cd frontend
      script:
        - docker --version
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --no-cache -t marco79423/mysite-frontend:latest .
      after_success:
        - docker push marco79423/mysite-frontend:latest
        - |
          if [ ! -z "$TRAVIS_TAG" ]; then
            docker tag marco79423/mysite-frontend:latest marco79423/mysite-frontend:$TRAVIS_TAG
            docker push marco79423/mysite-frontend:$TRAVIS_TAG
          fi
    - sudo: required
      language: python
      services:
        - docker
      before_script:
        - cd backend
      script:
        - docker --version
        - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
        - docker build --no-cache -t marco79423/mysite-backend:latest .
      after_success:
        - docker push marco79423/mysite-backend:latest
        - |
          if [ ! -z "$TRAVIS_TAG" ]; then
            docker tag marco79423/mysite-backend:latest marco79423/mysite-backend:$TRAVIS_TAG
            docker push marco79423/mysite-backend:$TRAVIS_TAG
          fi
