version: '3.6'
services:
  frontend:
    image: marco79423/mysite-frontend
    volumes:
      - "logs:/logs"
  backend:
    image: marco79423/mysite-backend
    command: main
    depends_on:
      - memcached
      - redis
    volumes:
      - "./content:/content:ro"
      - "logs:/logs"
  backend-celery-worker:
    image: marco79423/mysite-backend
    command: celery-worker
    depends_on:
      - redis
    volumes:
      - "logs:/logs"
  backend-celery-beat:
    image: marco79423/mysite-backend
    command: celery-beat
    depends_on:
      - redis
    volumes:
      - "logs:/logs"
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - "./conf/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./static:/static:ro"
      - "logs:/logs"
  memcached:
    image: memcached:alpine
  redis:
    image: redis:alpine
    command: ["redis-server", "--appendonly", "yes"]
volumes:
  logs: