version: '3.6'
services:
  frontend-dev:
    image: marco79423/mysite-frontend-dev:latest
    depends_on:
      - backend-dev
  backend-dev:
    image: marco79423/mysite-backend-dev:latest
    volumes:
      - "backend-static-dev:/app/static"
      - "backend-media-dev:/app/media"

  frontend:
    image: marco79423/mysite-frontend:latest
    depends_on:
      - backend
  backend:
    image: marco79423/mysite-backend:latest
    volumes:
      - "backend-static:/app/static"
      - "backend-media:/app/media"

  proxy:
    image: nginx:alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend-dev
      - backend-dev

      - frontend
      - backend
    volumes:
      - "/etc/letsencrypt/live/marco79423.net/fullchain.pem:/fullchain.pem:ro"
      - "/etc/letsencrypt/live/marco79423.net/privkey.pem:/privkey.pem:ro"

      - "./proxy/nginx.conf:/etc/nginx/conf.d/default.conf:ro"
      - "./proxy/static:/static:ro"

      - "backend-static-dev:/backend-static-dev"
      - "backend-media-dev:/backend-media-dev"

      - "backend-static:/backend-static"
      - "backend-media:/backend-media"
volumes:
  backend-static-dev:
  backend-media-dev:

  backend-static:
  backend-media:
